import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNav from '@/app/ui/sidebar';
import '@/app/globals.css';  // Ensure this is imported

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hello World!!",
  description: "Generated by Osama",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-black text-white`}>
        <div className="flex h-full">
          <SideNav />
          <div className="flex-grow p-6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
